language: minimal
services:
- docker
before_install:
- docker pull dm874/deploy
stages:
- build-publish
- deploy
jobs:
  include:
  - stage: build-publish
    script: docker build -t $LOCAL_IMAGE . && sh docker_push.sh
  - stage: deploy
    script: sh deploy_webserver.sh
env:
  global:
  - LOCAL_IMAGE=webserver
  - secure: gLF4ihpqrbMa1mRet7C75qtYNl0fTT9tqgtCiRvsItVSEE76syv5r552Vo0FOgTJM5j9vlPQ8WmmNUT/gTwbLp3vaYPMtA2ivtd0Lra7O3q2Bf6U/qI91fP/6bpgtFYsrc65gJbUA6XLuOFFTKlimojj6EVkSK1URdYMrzES7dgdrDBAYiz4uf1NanO5ziqcLZJOe9ShBNo+gIf2keRE4fORJnFUT2S+eAH8jXmGv6ACchlL+DueBKftJC+mY0RWeL6JzlDUYekZytCn/htfzGj0soSy+HNgRPE2iNGW56+0UB1bbuxYyZJ9HlDyXzBtvZsyo2Eod/+vGU0x0AaN71BmUQMonpBcBZhoi8e/WNcT9MieiRVph59C4iLgI+Dkd+idluDgWlbTOwxb/wk8ziUjocqSJ4P++G+oVM9ZgTEKbAISZUhGyqMBrtL/trsFvnC68KzNJr0G1ugwNHsZFnlv4G4c7J/MpIV6Lx+NF13VgSewvpbARYNGeHlVuCuzCmPGzhEbFcyxqgB2HmfQYBiv92V7Uq8+yFHRTFYg5VD2rJnHokMHRks978GqKhZ7kBMHgSOkeTupn+aKTZTAJIt7U9cgVeGsHNE2ELC/8pNBhIU81ayZpxGJ58YHUaiJQz2RHgOdKVSNfwIQW9l7SifOfIQ63PhKLRajigRUoHw=
  - secure: BImvxixgjkZ8+C5WmbeEk+jwHu3b4AQ5F0p6pvalPjhfpKr1VQAdC61ZAto2CFvAYfIeSCVb0QaoPz/ek7x1jNCkqu4hj/XvYPd4z9AP/MoVZNuOPgCLNSpgMs/aW8AJ9GgcbMrSHi7/wVCaeSLiG3JnLVyBwdgcmYCUfsVxTi3E4TAOik3KE/+hBy0usQDHQvB2O6b+mxt6Y3w6B32zk3mQWwG2P4EIevSYwKiRG8iGQ+2xZOupMQ47IrI1+qtPKV58RMQNGSCqiadgVX7ucPTlCHqRgnTDa6dSQPyBU1/OnT4BF0vIwoZN58xxQnRC7myIxCd5pWcqQE45Ul47lAyopWfM62zSj43p3f/ZWZFGO73lw1vl6iRC1JFSvtvpxQCrkL6t351AjEkvq5z+f0LAjH+aBHbs6nF5YWTln00Mly/hqewpiUXEYLK6ycw5wy9STt3D1qZdHMlaeN6TkLz/FwDYF15ZliLgdLSDo+6REQ7gcu0fVSC9owamCjEggoy51Jp4bk+DWm0dFJzLEY6w305rUyx+ptXNghcZr6BJnTzYhDckRus+RBtkQ016hZTWQkRLrExsQX8VlaYI2VOwezp2X2mdgtL5PuQtXj4PgsmKkLiKgprTDiSLDLhHSmqd4blbib8ajYifXFgYu2vPGfNunSF6fvE/b9ThSMg=
  - secure: TXsw3ec4ZD1czC30wr3JGislgGlWVK9m+PtGVzZjRmoR0U9KkpjQOnKNIRpEQD2judcJQ1e35hApuV1ivf1Ooh9I8KT3rjRdzdjYIkOiO/6EKzox8MTqmRssbw+Lp6PjvHvZVTBvYB0Gzfa/ruroJw2nAAsGd5lR9YjhXBAuu9ntn7UNBO/1KCc03WTSabTkHGPRVvGJCYRxv3tQ3kEaztpUUtXprMUBE9/Sp+AFtmZwcS8LNdf+AMsCHExJ68lK+KUzqym68l/YKO7d/vN73wWtTR+rR3NfJmEiUc0mCs17Fh60X01RK9BeLxM6ISuIZ0PkC52sYuBf33Ayuz2dI+jrP8jvA70aGeg255j2LvHXMpZkrFySsQ4Dp8jXCayWT/do+1mVJi1ZjoHdcZs8Cq+Je5CSK0P+G36CWbNhL+V0noQDNL7wAzQ+rd+GcCOh0QxiehzwG3sFh2PT4q9vUu5OxIHxQ+XV4ogpShoeHYm7TJjNE+sNRaHexVbWL8cQ+2+MZhRtaGWlmu7vwWiJAgxEJHi1+P06pm5zOeBq00trYdEOp5m5dEW45EH6fHynCGc4c3FzbVmhVSX6y3bIXBDxR8m2UZ4Ftc+6WJQurmAGwYY1aujDQ/ztWBc8/1v94QSe1IyFQX9r7EdrQ8LDrxlGhJbpcFFGXnyrwYLY5aI=
