#!/bin/bash

docker run -t dm874/deploy \
	-e KUBERNETES_TOKEN=$KUBERNETES_TOKEN \
	-e DOCKER_IMAGE_SLUG=$DOCKER_SLUG \
	-e DOCKER_IMAGE_TAG=$TRAVIS_COMMIT \
	-e SERVICE=$SERVICE \
	-e CONTAINER=$CONTAINER
