apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
  labels:
    app: webserver-service
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: webserver-port
  selector:
    app: webserver
