apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webserver
spec:
  replicas: 1
  serviceName: "webserver"
  selector:
    matchLabels:
      app: webserver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcs-key
      containers:
        - name: webserver-container
          image: WEBSERVER_IMAGE
          imagePullPolicy: Always
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: ROUTE_MESSAGE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: router-config
                  key: ROUTE_MESSAGE_TOPIC
            - name: CODE_SNIPPET_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: jolie-exec-config
                  key: JOLIE_EXEC_CONFIG_TOPIC
            - name: CODE_SNIPPET_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: jolie-exec-config
                  key: JOLIE_EXEC_GCS_BUCKET_NAME
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          envFrom:
            - configMapRef:
                name: redis-connection-config
            - configMapRef:
                name: code-snippet-storage-config
            - configMapRef:
                name: webserver-config
            - secretRef:
                name: jwt-secret
            - configMapRef:
                name: kafka-connection-config
            - configMapRef:
                name: jolie-exec-config
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "1500Mi"
              cpu: "2000m"
